scripts/install-alsa-config.sh
=> Fix permission in install-alsa-config.sh

HACKING.md, scripts/configure-driver.sh, scripts/install-deps.sh
These are no longer necessary now the 4.9 kernel is available.
=> Remove stretch instructions

scripts/configure-driver.sh, scripts/install-alsa-config.sh, scripts/install-services.sh
Add UID checks. Remove extra sudo calls. Add copyright header.
=> Update setup scripts.

.travis.yml
We only run pep8 and the tests.
=> Add a very basic travis config.

checkpoints/check_audio.py
=> Update reference for fixing the audio driver for the VoiceHAT.

HACKING.md
The project setup instructions for API credentials are located in:
https://aiyprojects.withgoogle.com/voice#users-guide-1-1--connect-to-google-cloud-platform
=> Added the direct link

src/main.py, src/speech.py
Fixes #12. This is based on Glen's change, but refactored a little.
=> Implement follow-on queries

.travis.yml, requirements.txt, scripts/install-deps.sh
Extract pip dependencies into requirements.txt. Manually install some
packages via apt that are listed in install-deps.sh.
=> Also install required python packages when running on travis.

scripts/install-deps.sh
This fixes #38 by making sure we create the virtualenv with the right
owner.
=> Determine the owner of the directory with `ls`

requirements.txt, src/auth_helpers.py, src/main.py
- remove auth_helpers dep
- add google_auth_oauthlib dep
Fixes #67
=> switch to google-assistant-grpc

src/audio.py
See https://github.com/google/aiyprojects-raspbian/issues/75
=> check if processor is in self._processors before removing it

checkpoints/check_audio.py, checkpoints/load_test.py, src/aiy/audio.py, src/main.py, src/tts.py
Also resolved some of the PEP8 warnings. There is still one left on the
long URL in src/main.py. I am not interested in changing that. PEP8 has
its problems.
Tested:
Ran src/main.py and played with the Google assistant for a bit.
Looks like it's working.
=> Move audio to aiy.audio

src/aiy/_apis/_speech.py, src/aiy/_drivers/_alsa.py, src/aiy/_drivers/_button.py, src/aiy/_drivers/_led.py, src/aiy/_drivers/_player.py, src/aiy/_drivers/_recorder.py, src/aiy/_drivers/_tts.py, src/aiy/assistant/_auth_helpers.py, src/aiy/assistant/grpc.py, src/aiy/audio.py, src/aiy/cloudspeech.py, src/aiy/voicehat.py, src/assistant_grpc_demo.py, src/cloudspeech_demo.py, src/led.py, src/main.py
Most of the modules are much easier to use now. Makers no longer need to
create classes/specify complicated arguments.
Modules added:
- aiy.audio: recorder, player, say (TTS)
- aiy.voicehat: LED, button
- aiy.cloudspeech: cloudspeech APIs
- aiy.assistant.grpc: assistant APIs
Demos added:
- cloudspeech_demo: demonstrates how to control the LEDs via voice commands.
- assistant_grpc_demo: Google Assistant.
=> Add core aiy modules and two demos.

src/aiy/_apis/_speech.py, src/aiy/_drivers/_alsa.py, src/aiy/_drivers/_button.py, src/aiy/_drivers/_led.py, src/aiy/_drivers/_player.py, src/aiy/_drivers/_tts.py, src/aiy/assistant/auth_helpers.py, src/aiy/assistant/grpc.py
This CL contains several formatting changes.
- Leaving a vertical space between file comment and the header.
- Making private members private (prefixed with a single underscore)
- Making aiy.assistant._auth_helpers aiy.assistant.auth_helpers. So
makers building their own app can make use of the convenient tools to
authenticate with Google Assistant APIs.
Tested:
- Deployed to RPi3 + VoiceHat.
- Ran src/assistant_grpc_demo.py.
=> Some formatting changes.

src/aiy/_drivers/_tts.py
This was discovered on the MagPi forums. Fixes #101.
=> Improve TTS quality

checkpoints/check_audio.py, src/aiy/_drivers/_recorder.py, src/aiy/audio.py
This CL fixes #110 
Tested:
Ran all checkpoints scripts
Ran assistant_grpc_demo.py
Ran assistant_library_demo.py
Ran cloudspeech_demo.py
=> Fix check_audio.py.

scripts/install-deps.sh
=> Upgrade to google-assistant-library==0.0.3

checkpoints/check_audio.py, checkpoints/check_cloud.py, checkpoints/check_wifi.py, checkpoints/load_test.py
Remove the warnings and errors from the checkpoints folder.
I checked the warnings and errors using [Pylama](https://github.com/klen/pylama).
=> Remove warnings and errors from checkpoints

README.md
I haven't restored the Travis badges as the build is failing on the
voicekit branch.
=> Improve README on voicekit branch

src/aiy/_apis/_speech.py
=> Don't hardcode home directory

src/assistant_library_with_local_commands_demo.py
This PR is split off from #149:
@drigz commented on #138 that a PR to add this action would be welcome. There was a PR to add this a few days ago that was killed by the submitter, so I thought I would try to revive it. I initially had issues getting the "ip address" command to work, but ~~capitalizing "IP"~~ converting the command string to lowercase made Assistant recognize it.
=> Added "IP address" action that says Pi's IP

README.md
The link of the logo is https://aiyprojects.withgoogle.com/static/images/icons/aiy-square-logo.svg
=> Adding the AIY Projects logo

shortcuts/check_audio.desktop, shortcuts/check_cloud.desktop, shortcuts/check_wifi.desktop
The paths in shortcuts were old
=> Correct paths in shortcuts

HACKING.md, src/aiy/_drivers/_led.py, src/aiy/_drivers/_status_ui.py, src/aiy/_drivers/_tts.py, src/aiy/audio.py, src/aiy/cloudspeech.py
These were lost in the merge (a4298c65). Summary of changes:
- Fix instructions for using the Voice Kit on Stretch (#187)
- Make it easier to turn the LED off (#167)
- Fix crash with trigger sound (#163)
- Let user code control TTS (#185)
- Enable hotwording with Cloud Speech (0b4972b4)
=> Restore changes from the voicekit branch

README.md
=> Point to aiyprojects branch from master README

README.md
=> Point to aiyprojects branch from voicekit README
