google/aiyprojects-raspbian

- src/tts.py
Without this fix, the following issue occurs when a non-ASCII input is passed to the "say" method. In this case I told the device "stop", after which the Google Assistant API returns "I don\u2019t know how to answer that" (note the \u2019, i.e. the "right single quotation mark"). With the fix it works properly.
It seems that subprocess.call ends up calling native CPython code, where all arguments are passed to PyUnicode_FSConverter, which tries to encode each string using the PyUnicode_EncodeFSDefault() encoding. In this case that encoding seems to be ASCII, which then causes the error. When we do the encoding to bytes ourselves ahead of time then PyUnicode_FSConverter will just return those bytes as is, thereby avoiding the error.
Logs showing the error:
[2017-05-06 18:22:51,403] …
> Properly encode UTF-8 input passed to pico2wave

- checkpoints/check_audio.py
- checkpoints/check_cloud.py
- checkpoints/load_test.py
- scripts/install-deps.sh
- scripts/install-services.sh
This means things aren't broken if the user clones into
~/aiyprojects-raspbian, for example.
> Don't hardcode the path to the repo

- HACKING.md
This is required because it uses shell redirects to write the service files, so must be root.
> Use sudo for install-services.sh

- scripts/install-deps.sh
Currently, a user who follows the instructions in HACKING.md won't
install the config files, so they'll run into the crash described in
issue #10. This avoids them being affected by the crash.
> Install config files along with deps

- src/main.py
Fixes #10 by avoiding a crash when no config file is present.
> Add defaults for config file locations

- scripts/install-deps.sh
`python3-rpi.gpio` is required, `python3-pysocks` just gets rids of a warning.
> Add missing deps needed for vanilla Raspbian

- HACKING.md
- README.md
- Add a reference to HACKING.md in README.md for better discoverability.
- Add new subsection on installing the dependencies: `git` needs to be
explicitly installed and the directory under which the repository must
be cloned needs to be specific as it is hardcoded in some scripts.
> Update info on HACKING.md

- src/main.py
This is important with the Assistant, as it doesn't always give you an
audio response, even when it handles the command (eg for changing the
volume). It also helps when using the Cloud Speech API, as false
triggers aren't as noticeable if they don't trigger a command.
@ensonic / others, if you think these errors are important for some users, maybe we could hide them behind an option? But I'd prefer to keep it simple if possible.
> Stay silent when we don't recognize a command

- src/main.py
- src/status-monitor.py
We try /run/user/\<uid\>/ and /tmp/, in that order. This should ensure
functionality across a wide range of distros.
Fixes #23.
> Use the right location for the pidfile

- systemd/status-led.service
This fixes #54, caused by breakage introduced when I moved
configargparse from a system install (which required the stretch
package) to the virtualenv (#16).
> Use virtualenv for running the status-led service

- config/voice-recognizer.ini.default
- src/main.py
Add an optional trigger sound confirmation, useful to know when it's actually listening when not using the voice hat hardware or any other led light.
> Add trigger sound confirmation

- src/audio.py
- src/main.py
Adding some improvments on PR https://github.com/google/aiyprojects-raspbian/pull/60
- Allow for trigger-sound path to start with "\~" by calling `os.path.expanduser` the trigger-sound argument if one exists. If expanduser is called on a string that doesn't start with '~' this results in a [no-op](https://docs.python.org/2/library/os.path.html#os.path.expanduser) and shouldn't affect current behavior
- Add a log message when the trigger-sound argument is present, but does not exist according to os.path.exists to help with debugging.
Random fix I found while coding:
-  Fix spacing of log message in Player.play_wav
> Improve sound confirmation code

- .coveragerc
- requirements.txt
- src/action.py
- tests/test_change_light_color.py
This adds Philips hue support using the `phue` library. 
It would be nice to configure the hue bridge in the global configuration file, but I wasn't able to find a nice way to pass this into the `actions.py` class. As such I've forced the user to set it for each actor request. 
Example use where the hostname for my Hue bridge is `philips-hue`. 
`actor.add_keyword(_('change to purple'), ChangeLightColour(say, "philips-hue", "Lounge Lamp", "FFFFbe"))`
> Add Philips Hue action type

- src/action.py
Adds commands to shutdown and reboot the pi.
> Added shutdown and reboot commands

- src/tts.py
This avoids resonance on both Chris's and my Voice Kits.
The voice still sounds tinnier because of the removal of the bass
frequencies. It may be possible to make the filter less aggressive
while still avoiding resonance - I will investigate this once I have
more kits for testing.
> Reduce the gain by 4dB on the TTS equalizer

- config/voice-recognizer.ini.default
- requirements.txt
- scripts/install-deps.sh
- src/actionbase.py
- src/main.py
- tests/test_actor_base.py
This requires installation of the wheel for the Google Assistant
Library, which includes a closed-source hotword implementation.
> Use the Assistant Library for OK Google hotwording

- src/action.py
The speech recognition wasn't very good at recognizing "pi" but
"raspberry" seems to work better.
Fixes #69.
> Use "raspberry" instead of "pi" as power keyword

- src/aiy/common.py
- src/led.py
This change includes two common drivers:
1) Button - A GPIO-based button driver that automatically debounces the
GPIO signal.
2) LED - A GPIO- and PWM-based LED driver that supports a set of simple
LED patterns.
Tested:
Manually tested on a RPi3 + VoiceHat.
> Add AIY common drivers.

- scripts/pre-commit
It appears that we are working with a max line length of 100. If that's
case, let's update the pre-commit file to reflect that (instead of 120).
> Update precommit hook's max line length.

- scripts/install-deps.sh
- src/aiy/_drivers/_tts.py
This is possible now that pico2wave has had its volume reduced and
doesn't generate clipped output audio. It should improve startup time by
one or two seconds since it doesn't import scipy.signal.
This PR depends on #105.
> Remove dependencies on scipy and sox

- src/aiy/audio.py
This fixes #109 
Tested:
Changed $HOME/.config/voice-recognizer.ini to use en-GB.
Ran src/main.py --cloud_speech
Verified the TTS sound has a British accent.
> Make sure aiy.audio.say uses the aiy.i18n's language.

- README.md
- scripts/install-deps.sh
Fixed a bug in install-deps.sh on Raspbian Stretch (mentioned in #119), where calling virtualenv raises an error saying "command not found".
I believe the cause of the virtualenv issue is that in Jessie, the python3-virtualenv package contains an old version of virtualenv, but install-deps.sh also runs pip to upgrade the virtualenv package, which is when the virtualenv command gets added. In Stretch, the python3-virtualenv package contains the latest version of virtualenv but does not add the command, and the pip command does nothing because the latest version is already installed.
Installing the virtualenv package is an alternative method of adding the command, and it can be substituted in the list of packages for python3-virtualenv because it includes it as a dependency.
Also, I …
> Fix bug in Stretch where virtualenv command not found.

- src/aiy/_drivers/_status_ui.py
flake8 testing of https://github.com/google/aiyprojects-raspbian on Python 3.6.2
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/aiy/_drivers/_status_ui.py:54:13: F821 undefined name 'self'
self.trigger_sound_wave = os.path.expanduser(trigger_sound_wave)
^
./src/aiy/_drivers/_status_ui.py:60:13: F821 undefined name 'self'
self.trigger_sound_wave = None
^
2       F821 undefined name 'self'
```
> Don't forget self

- HACKING.md
Remove warning for Stretch users now that the libttspico-utils package has been added to the Raspbian repository.
> Remove warning for Stretch users

- src/main.py
These are ignored currently, so it's misleading to have them. The voice
recognizer always uses the default device, which can be configured by
the user.
See #98.
> Remove input/output_device options

- src/aiy/_drivers/_button.py
- src/aiy/_drivers/_led.py
- src/aiy/assistant/auth_helpers.py
- src/aiy/assistant/grpc.py
- src/aiy/audio.py
- src/aiy/cloudspeech.py
- src/aiy/voicehat.py
- src/assistant_grpc_demo.py
- src/cloudspeech_demo.py
I changed some conditions to do them in a more "pythonic" way.
Thank you!
> Change some conditions to be more pythonic

- HACKING.md
- systemd/voice-recognizer.service
This PR is my attempt to fix #148. I've added back the files `HACKING.md` and `systemd/voice-recognizer.service` which were in the master branch. I also updated the instructions in `HACKING.md` to work with the voicekit branch.
IMO these files are too useful to not be present in the new branch, and having them there doesn't change the way that this project behaves for anyone who doesn't want to use them.
The way the `install-services.sh` script is currently written, it will automatically add any services in the `systemd` folder to the `/lib/systemd/system` folder on the Pi, including `voice-recognizer.service` if it is present. It will also replace any references to `/home/pi` in the service file, updating them to the correct installation folder. However, the service will never run unless …
> Add instructions for setting up on Raspbian in voicekit branch.

- README.md
I forgot to include this in PR #149. This commit restores the line mentioning HACKING.md in the voicekit branch (which was originally added in #36).
IMO having this in the readme is helpful, because its how I figured out how to set up Assistant on my Pi. I would have missed that these instructions existed otherwise and wasted a lot of time.
> Add mention of HACKING.md to readme

- src/aiy/_drivers/_status_ui.py
When trying to remove a trigger sound (passing None), it falls through and throws an error when trying to find a None file. Added a return statement to stop this happening.
> Fixed trigger sound wave null bug when removing trigger sound

- src/aiy/_drivers/_tts.py
- src/aiy/audio.py
Like the title says, this will expose the volume and pitch for tts to the user code. 
It can be set/get globally with:
```
aiy.audio.set_tts_volume(50)
volume = aiy.audio.get_tts_volume()
aiy.audio.set_tts_pitch(140)
pitch = aiy.audio.get_tts_pitch()
```
Or set individually with say:
```
aiy.audio.say('Good bye!', volume=50, pitch=140)
```
> Expose tts volume and pitch to the user code like we do with lang.

- src/aiy/_drivers/_led.py
As `state` is checked with `if state`, the valid state change to `0` (LED_OFF) is ignored by the driver.
As a result its not possible to use the LED_OFF state in the `_state_map` of `_status_ui.py`.
Some people would like to turn of the constant flashing of the LED in ready state (`DARK_BEACON`) (#2, #15). This changes makes this as easy as changing the ready state in the state_map.
> Narrow check for state change in led driver

- HACKING.md
This allows the correct ALSA state to be configured, and prevents the
volume widget writing an invalid config. Fixes #183.
> Reboot before installing ALSA config

- requirements.txt
- src/aiy/_apis/_speech.py
The v1beta1 endpoint has been shut down, so this is necessary for using
the Cloud Speech demo now.
See #205.
> Update to Cloud Speech v1

- src/aiy/cloudspeech.py
> add immediate option for cloudspeech recognize

- requirements.txt
- scripts/install-deps.sh
- src/aiy/_apis/_speech.py
- src/aiy/assistant/device_helpers.py
- src/assistant_library_demo.py
- src/assistant_library_with_button_demo.py
- src/assistant_library_with_local_commands_demo.py
This doesn't update from v1alpha1 of the gRPC API to v1alpha2, which is to follow, but appears to be mostly search-and-replace.
I've not yet tested this on the Voice Kit hardware (or even on a machine with a microphone - I only have access to a Chromebook right now). I'm concerned that upgrading the library breaks the button+library demo as reported in #204. However, that's separate to the Device / Model ID logic.
The Device ID is currently unused, but it may be required for the gRPC API, and would be required if we want to use Device Actions, so it makes sense to keep it.
@proppy, how can we specify the language? I can't see any way to specify it for the Google Assistant Library, and the gRPC docs still say [only en-US is supported](https://developers.google.com/assistant/sdk/reference/rp …
> Update to google-assistant-{library,grpc}==0.1.0

- README.md
- src/README.md
The root README.md is documentation for the GitHub repo, shown on the
https://github.com/google/aiyprojects-raspbian. src/README.md is
documentation for the API, which can't contain relative links to files
in the GitHub repo.
Fixes #214.
> Improve the two README.md files
